mobile first
alizaamir123/setup-mobile-first pull request #1
Opened 2023-03-22 20:56 UTC by alizaamir123

I create an index page and in index page I make navbar and banner and in banner I write about myself.
Then I create a CSS file and give styling.

2023-03-22 22:58 UTC, ouasamine reviewed
Hi @alizaamir123 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README file.

**Friendly reminder**: You should make sure that your repository looks professional before review. Please take a step back apply 5 simple rules from this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) (it will be easy as you can use the template provided there).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-22 23:16 UTC, abdulhamiid requested changes
Hi @alizaamir123 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ ❌ 

- [ ] You have submitted a project, that does not have a professional README.  
- [ ] A README file is a guide that gives users a detailed description of a project you have worked on. so it is always necessary to have a descriptive README.

#### MIcroverse Readme Template 👇 
![image](https://user-images.githubusercontent.com/78251927/227058447-f37ae602-2990-418b-a69f-9e05faa01e58.png)

### **Your Readme** 👇 

![image](https://user-images.githubusercontent.com/78251927/227058573-dd59a362-1926-4e53-85e5-2422be45d63d.png)

- [ ] Please kindly note that all main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo and their contents are customized accordingly. The only optional section is FAQ.

- [ ] Please kindly make sure to customize the readme CAREFULLY so as to keep the correct display format of the template. 🙏

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-23 13:31 UTC, Gambit142 commented on README.md
> +LinkedIn: AlizaAmir
- [ ] Kindly use the recommended Microverse README template (https://github.com/microverseinc/readme-template) for this project and all projects that you would do in Microverse. When adopting the template, kindly do the following:

- Remove the Microverse logo. If you have your logo, you can use it, otherwise, I would advise you to remove the logo. 👍 
- Personalize the project name and project summary to the name of your project and a summary of what you implemented. 👍 
- In the **_Tech stack section_** of the README, kindly remove the technologies listed in the `Client`, `Server` and `Database` subsections. Those sections contain technologies that were not used in this project. Kindly remove the `Server` and `Database` subsections and replace those in the `Client` subsections with HTML and CSS. 👍 😎 
- In the **_Key Features section_**, kindly add 1-3 things that you accomplished in this project. I would also advise you to get used to adding these features because you would do that for every project in Microverse and possibly in the professional world. 👍
- If you are not required to deploy the application, you can remove the **_Live Demo section_** of the README.md file. If you are required to deploy, then the link to the deployed project should be pasted under this section. 👍
- In the **_Getting Started Section_**, kindly do the following for the subsections:
  -  In the **_Prerequisite subsection_**, kindly add packages or applications that would be needed to start this application on the local machine. You can include NPM, a browser, a code editor, git and any other thing you can think of. 👍  
  - In the _Setup subsection_, kindly include ways to clone this project and change the directory to the directory of the project. See the example below as a guide:

```sh
  cd my-folder
  git clone git@github.com:myaccount/my-project.git
  cd my-project
```
  - In the **_Install subsection_**, you can indicate ways to install the linters locally and also to run them locally. 👍 😎
  - The _**Usage**_ subsection should contain ways to run the project in the browser if while the Run tests subsections should contain the commands for running the tests written in the project. 👍 😎 
- The **_Authors section_** should contain the social media handles of the owner of the repository and all other collaborators
- The **_Future Features_** section of the README.md file. The Future Features section should contain 1-3 features that can be implemented in the future. Most times, this section acts as a reference to you and future collaborators whenever you want to improve your projects in the future 💻 😎 
- The **_Show Your Support_** Section should communicate to people ways they can help advance the project or give a star to the project if they like it 👍 😎 
- The _**Acknowledgement**_ section should contain information, links and appreciation for those who spurred or contributed to the success of the project 💻 
- The _**FAQ**_ section is the only optional section and it should contain frequently asked questions about the project and answers to those questions 😎 👍 
- The _**LICENSE**_ section should contain permissions given as regards the use of the project. I would advise you to follow the guide on the right side of the article that I would paste below to set a valid LICENSE 👍 

https://choosealicense.com/licenses/mit/

2023-03-24 19:05 UTC, Lizdev-05 requested changes
Hi @alizaamir123, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<img src="https://media0.giphy.com/media/Ty9Sg8oHghPWg/giphy.gif"/>
## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README file. Kindly make use of Microverse README [template.](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-24 20:29 UTC, ahmetbozaci commented
### Hello @alizaamir123 
### _This is an additional review as a result of the second opinion request._ 

- 👔 It is imperative to create professional and informative readme files for all projects. To meet this requirement, it is recommended to utilize the Microverse readme template available at the following [link](https://github.com/microverseinc/readme-template) By filling out the sections of the template with relevant information about your project, you can create a comprehensive and effective readme file that communicates the purpose, functionality, and features of your project. 
- Readme file should include all required sections, only the FAQ section is optional and you fill these sections according to your project.
![image](https://user-images.githubusercontent.com/38635158/227630848-85319fe8-6da5-41ce-bff0-6a385f261fcd.png)

👔 Some key improvements are required for the project readme file:

- [ ]  A project description is missing, which is an essential component of the readme. Therefore, kindly add a brief description of the project to provide an overview of its purpose and features.

- [ ]  The tech stack used in the project should be listed in the readme. Therefore, kindly fill in the relevant information to give readers an idea of the tools and technologies employed.

 

- [ ] The template text that reads "Describe between 1-3 key features of the application" should be deleted. You should delete all template texts in your readme file.

 

- [ ] The readme should include a contributing section that outlines the guidelines and steps for users to contribute to the project. Therefore, kindly add this section and fill it in properly to encourage community involvement.

 

- [ ] Ensure that the table of contents is working correctly so that when a user clicks on any section, it takes them to the appropriate part of the readme. If any of the links are not functioning correctly, kindly fix them to improve the user experience.


_Based on the feedback provided, it is necessary to make some changes to the project to ensure compliance with the requirements and guidelines. Therefore, kindly review the feedback provided and make the necessary adjustments to the project. Once you have made the required changes, kindly resubmit the project for further review and feedback._ 
___

### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2023-03-24 20:29 UTC, Eternalgratis commented on style.css
> +}
- The project requirements stated that your responsive values should be in percentage. Kindly implement this so it's easy for your page to respond to both desktop and mobile devices

2023-03-24 20:39 UTC, Eternalgratis commented on README.md
> -set and mobile first project
- Kindly add a descriptive summary of your project in the highlighted section above just like the previous reviewers have suggested. This is important for anyone visiting your page to know what your project is all about and it is also an industry-standard practice

2023-03-24 20:49 UTC, Eternalgratis commented on README.md
> +### Tech Stack <a name="tech-stack"></a>
- Kindly add your stack here. Eg  Html and CSS, just like what you used in this project. Again, it is important for collaborators, potential employers, or reviewers to be able to have basic information about your project from your README.

2023-03-24 20:55 UTC, Eternalgratis requested changes
# Status: Required Changes
Hi @alizaamir123 , 

Good job so far!
There are some issues that you still need to work on in order to go to the next project, but not to worry, you are almost there!

## Highlights
✅ You used the correct Gitflow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Required Changes ♻️
 Check the comments under the review. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise. **

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 22:40 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @alizaamir123  , I'm @MaganaAsiati , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>


## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] Check the comments under the review.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

2023-03-24 22:40 UTC, MaganaAsiati commented on index.html
> +
- [ ] [ OPTIONAL] You did great here but kindly remove this part as it has not yet part of the requirement you will implement it in the next project :+1:

2023-03-24 23:29 UTC, merged