Finish mobile
alizaamir123/setup-mobile-first pull request #4
Opened 2023-03-28 19:21 UTC by alizaamir123

-Create Index.html
-Create Style.css

2023-03-28 20:05 UTC, joramot commented
Hello Aliza, your effort has been very good but you have problem with the work environment and need to set up it, I cloned your repo and tried it to run linters tools but didn´t, kindly te suggest fixing it.

2023-03-28 20:42 UTC, BregornOriginal requested changes
## Hi @alizaamir123  

## Good job so far!
## There are some issues that you still need to work on to go to the next project but you are almost there!

***[OPTIONAL] It would be great to add a better description to your Pull Request, in this way you can show your work what you did in this branch***

![one-step-closer-one-more](https://user-images.githubusercontent.com/93630700/228361940-8c618b67-246b-422a-8ea6-4ef54485f5c7.gif)

## Highlights

✅ Linters are passing
✅ Good commit history


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 20:42 UTC, BregornOriginal commented on index.html
> +    <button type="button" class="submit-button">Get in touch</button>
As you are creating a form, to submit it you need to create a button with type=`submit`. As default, a button has the type `submit`. So you can replace the type of the button or just delete it.

In this way the form will be sent and works correctly 🥇

2023-03-28 21:16 UTC, OyePriscilla approved these changes
Hi @alizaamir123 👍 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Create forms with HTML5 validations ✔️
All fields have the correct type ✔️
Implement the button interactions ✔️

## Optional suggestions

- [ ] Please kindly format your README file properly in accordance to this [template](https://github.com/microverseinc/readme-template). **Ensure to remove the placeholder in "Key features" header, add the "Contributing" header with appropriate details and fill up other necessary sections of the "Getting Started" header.** 👍 All these will make your repo looks more professional and informative. 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 21:16 UTC, OyePriscilla commented on index.html
> +    <form action="https://formspree.io/f/{form_id}" method="post" class="html-forms">
- [optional] Please kindly take note at the moment that the `form` is not submitting to the `url` because you did not provide a valid` form_id`. I think you will have to [register with formspree](https://formspree.io/register) before you can have access to the` form_id`. ℹ️

2023-03-28 21:16 UTC, OyePriscilla commented on index.html
> +  </ul>
- [optional] Please kindly add this shape according to the given template. 👍 

##Figma design
<img width="282" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/228354721-6bed09c6-582a-4f09-916f-19d1c1b12c06.png">

2023-03-28 21:16 UTC, OyePriscilla commented on index.html
> +    <textarea id="message-field" name="message-field" maxlength="500" >Write me something...</textarea>
- [optional] Please ensure to give this input element padding-left and padding-top according to the design. 👍

2023-03-31 23:56 UTC, adel-gu approved these changes
# Status: APPROVED 🟢 

Hi @alizaamir123 👋🏼 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Well responsive website  ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 23:56 UTC, adel-gu commented on index.html
> +    <form action="https://formspree.io/f/{form_id}" method="post" class="html-forms">
- **[OPTIONAL]** As stated as  an optional from the previous  reviewer please consider giving the form action `https://formspree.io/f/{form_id}`  an appropriate form id by registering to [formspree](https://formspree.io/register) and setting up your form 👍🏼

2023-04-01 05:10 UTC, merged