Add accessibilities to portfolio
alizaamir123/setup-mobile-first pull request #7
Opened 2023-04-04 20:09 UTC by alizaamir123

This PR includes :
Add accessibilities in portfolio.

2023-04-04 21:19 UTC, tsohleDev requested changes
## Hi @alizaamir123 

Good job so far!
There are some issues that you still need to work on.

![163947610-e4d849d5-e69c-49b9-90bd-a4191f4e2856](https://user-images.githubusercontent.com/97100091/191558701-8ed50201-3123-435c-89d8-29edcb66c64d.gif)

## Highlights!
- README template ✔️ 
- Descriptive commits ✔️ 
- Good branch name   ✔️
- No linter errors  ✔️
- Descriptive pull request  ✔️
- All requirements met ❌

Hello ✋, you have done well creating your project 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

## Compliment
_Every comment with the [COMPLIMENT] prefix is not  a request, just a compliment at your skills_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@tsohleDev` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 21:19 UTC, tsohleDev commented on index.html
> +        <li><a href="#" title="medium icon"><img src="images/medium-icon.png" alt="" ></a></li>
- [ ] I suggest you follow the hierarchy of headers, at line 62 you have ``h2`` which is the heading of the section, and then within that section, you have another ``h2`` at line 70, I think it would be better if you used ``h3`` instead of ``h2`` to follow the hierarchy 😉 .

2023-04-04 21:19 UTC, tsohleDev commented on index.html
> +  <h1 class="form-supporting-text">I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</h1>
- [ ] I wouldn't advise using a ``h1`` tag more than once in a page as it is used to define the most important heading of the page 😉

2023-04-04 21:19 UTC, tsohleDev commented on index.html
[COMPLIMENT] Nice job at styling your page 💯  it is responsive and beautiful ☺️

2023-04-05 14:45 UTC, ShadyShawkat approved these changes
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 14:56 UTC, merged